language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
# command to install dependencies
install: "pip install -r requirements/test.txt --use-mirrors"
# command to run tests
script: make test
# Use X Frame Buffer to run selenium tests
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
